[package]
name = "base64-box"
version = "0.1.0"
edition = "2021"

[lib]
name = "base64_box"
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.22"
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3"
