const en = {
  mode: 'Input mode', tools: 'Tools', title: 'Local AI', experimental: 'Experimental',
  input: 'Input', output: 'Output', task: 'Task', language: 'Output language',
  tasks: { ask: 'Ask', translate: 'Translate', rewrite: 'Rewrite', summarize: 'Summarize' },
  placeholder: 'Ask a short question or paste a short passage…',
  privacy: 'This input stays out of tool matching, history and share links. Leaving Local AI clears the draft and releases the model.',
  download: 'Qwen2.5 0.5B · q4f16 · about 483 MB of weights, plus tokenizer and runtime files. Requires WebGPU with shader-f16 and enough device memory.',
  consent: 'Allow runtime and model downloads from jsDelivr and Hugging Face on this connection.',
  prepare: 'Download / load model', run: 'Run locally', stop: 'Stop', release: 'Release memory',
  clearModel: 'Delete model cache', clearConfirm: 'Stop this model and delete its cached files? Close other Local AI tabs first. Other tools and history will not be cleared.',
  cacheNote: 'Model files are cached when storage permits. Offline cold starts are not guaranteed; the pinned CDN runtime may still need a connection.',
  caution: 'Small-model output may be incorrect. No cloud fallback. Up to 1,024 prompt tokens and 256 new tokens; shorten long input rather than silently truncating it.',
  stoppedNote: 'Stopped output is incomplete. Loading is required again before the next run.',
  useOutput: 'Use as AI input', copy: 'Copy', copied: 'Copied', copyFailed: 'Copy failed. Select and copy the output manually.',
  status: { idle: 'Model not loaded', loading: 'Downloading / initializing', ready: 'Ready', generating: 'Generating', complete: 'Complete', stopped: 'Stopped', error: 'Action required', deleting: 'Deleting model cache' },
  errors: {
    insecure: 'Open this page over HTTPS (or localhost on this device).',
    unsupported: 'WebGPU is unavailable in this browser or device. The regular tools still work.',
    fp16: 'This GPU lacks shader-f16, which the selected model requires. No larger model will be downloaded automatically.',
    load: 'Model loading failed. Check the connection, storage and available memory, then retry.',
    generation: 'Generation failed. Release other GPU-heavy tabs, load the model again and retry a shorter input.',
    invalidInput: 'Enter some text and select a supported task and language.',
    inputTooLong: 'The input exceeds the character or token budget. Please shorten it.',
    worker: 'The AI worker could not run. Reload or try another WebGPU-capable browser.',
    timeout: 'The operation timed out and the worker was stopped. You can load the model again to retry.',
    cache: 'The browser could not delete the model cache. Check site storage permissions.',
  },
};
const zhTW: typeof en = {
  mode: '輸入模式', tools: '一般工具', title: '本地 AI', experimental: '實驗功能',
  input: '輸入', output: '輸出', task: '任務', language: '輸出語言',
  tasks: { ask: '問答', translate: '翻譯', rewrite: '改寫', summarize: '摘要' },
  placeholder: '輸入簡短問題，或貼上一小段文字…',
  privacy: '此處的輸入不進入工具匹配、歷史記錄或分享連結。離開本地 AI 時會清除草稿並釋放模型。',
  download: 'Qwen2.5 0.5B · q4f16 · 模型權重約 483 MB，另需 tokenizer 與 runtime 檔案。裝置須支援 WebGPU、shader-f16，並有足夠記憶體。',
  consent: '允許使用目前的網路，從 jsDelivr 與 Hugging Face 下載 runtime 和模型。',
  prepare: '下載／載入模型', run: '在本機執行', stop: '停止', release: '釋放記憶體',
  clearModel: '刪除模型快取', clearConfirm: '停止模型並刪除其快取檔案？請先關閉其他本地 AI 分頁。這不會清除一般工具或歷史記錄。',
  cacheNote: '儲存空間允許時會快取模型。尚不保證離線重新啟動可用；固定版本的 CDN runtime 仍可能需要網路。',
  caution: '小模型可能回答錯誤，不會自動改用雲端。提示詞上限 1,024 tokens，回答上限 256 tokens；過長輸入需自行縮短，不會默默截斷。',
  stoppedNote: '已停止，輸出可能不完整。下次執行前需要重新載入模型。',
  useOutput: '作為 AI 輸入', copy: '複製', copied: '已複製', copyFailed: '複製失敗，請選取輸出後手動複製。',
  status: { idle: '尚未載入模型', loading: '下載／初始化中', ready: '可執行', generating: '生成中', complete: '已完成', stopped: '已停止', error: '需要處理', deleting: '正在刪除模型快取' },
  errors: {
    insecure: '請使用 HTTPS 網址（或此裝置上的 localhost）。',
    unsupported: '此瀏覽器或裝置無法使用 WebGPU；一般工具仍可使用。',
    fp16: '此 GPU 不支援模型需要的 shader-f16。不會自動下載更大的模型。',
    load: '載入模型失敗，請檢查網路、儲存空間與可用記憶體後重試。',
    generation: '生成失敗。請關閉其他使用 GPU 的分頁，重新載入模型並縮短輸入後再試。',
    invalidInput: '請輸入文字，並選擇支援的任務與語言。',
    inputTooLong: '輸入超過字元或 token 上限，請縮短內容。',
    worker: 'AI Worker 無法執行，請重新載入或改用支援 WebGPU 的瀏覽器。',
    timeout: '操作逾時，已停止 Worker。可重新載入模型後再試。',
    cache: '瀏覽器無法刪除模型快取，請檢查網站儲存權限。',
  },
};
export const localAIStrings = (locale: string) => locale === 'tw' ? zhTW : en;
