// Bench harness comparing math-box (WASM) against mathjs (JS) on identical
// expressions. Run via: `node wasmModules/math-box/bench/compare.mjs`.
//
// Methodology:
//   1. Warm both engines with 1,000 full evaluations of each expression.
//   2. Time N evaluate-from-source iterations per engine per expression.
//   3. Report median over R runs to dampen GC noise.

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { arch, cpus, platform, release } from 'node:os';
import { gzipSync } from 'node:zlib';

const require = createRequire(import.meta.url);

const ITER = 100_000;
const RUNS = 5;

const cases = [
  { name: 'simple', expr: '1 + 2 * 3' },
  { name: 'medium', expr: '2 + 2^10 + log(10, 10000)' },
  { name: 'trig', expr: 'sin(PI/2) + cos(PI/3)' },
  { name: 'hex', expr: '0xff + 0b1010' },
  { name: 'factorial', expr: '5! + 10!' },
  { name: 'nested', expr: '(((1 + 2) * 3 - 4) / 5) ^ 2' },
  { name: 'large_int', expr: '1234567 * 7654321 + 99999' },
  // phase 2 — variables & user functions
  { name: 'var_assign', expr: 'a = 5; b = 7; a*b + a^2' },
  { name: 'user_fn', expr: 'sq(x) = x^2; sq(11) + sq(13)' },
  // phase 3 — bigint
  { name: 'bigint', expr: '9007199254740993n + 1n' },
  // phase 4 — fraction
  { name: 'fraction', expr: 'frac(1, 3) + frac(1, 4)' },
  // phase 5b — unit conversion via SI table
  { name: 'unit', expr: 'convert(unit(1, "km"), "m")' },
  // phase 6 — complex
  { name: 'complex', expr: '(2 + 3*i) * (2 - 3*i)' },
];

async function loadMathBox() {
  // Read the build output directly. An installed file: dependency can retain
  // an older WASM inode after wasm-opt replaces the package's binary.
  const mod = await import('../pkg/math_box.js');
  const bytes = await readFile(
    new URL('../pkg/math_box_bg.wasm', import.meta.url),
  );
  await mod.default({ module_or_path: bytes });
  return { mod, bytes };
}

function median(arr) {
  const sorted = [...arr].sort((a, b) => a - b);
  const m = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[m] : (sorted[m - 1] + sorted[m]) / 2;
}

function bench(label, fn) {
  // warm
  for (let i = 0; i < 1000; i++) fn();
  const samples = [];
  for (let r = 0; r < RUNS; r++) {
    const t0 = performance.now();
    for (let i = 0; i < ITER; i++) fn();
    samples.push(((performance.now() - t0) * 1000) / ITER); // µs per op
  }
  return { label, us_per_op: median(samples) };
}

async function main() {
  const { mod: mathBox, bytes } = await loadMathBox();
  const { evaluate: mjsEvaluate } = await import('mathjs');
  const command = (executable, args) => {
    try {
      return execFileSync(executable, args, {
        encoding: 'utf8',
        cwd: new URL('../../..', import.meta.url),
        stdio: ['ignore', 'pipe', 'ignore'],
      }).trim();
    } catch {
      return 'unavailable';
    }
  };
  const lines = [
    '# math-box Benchmark Report',
    '',
    'Generated by `bench/compare.mjs`. This is one measurement on the environment below, not a cross-machine performance guarantee.',
    '',
    '## Environment',
    '',
    '| Item | Value |',
    '| --- | --- |',
    `| Date (UTC) | ${new Date().toISOString()} |`,
    `| Source checkout commit | ${command('git', ['rev-parse', 'HEAD'])} |`,
    `| Checkout has uncommitted changes | ${command('git', ['status', '--porcelain']) !== ''} |`,
    `| CPU | ${cpus()[0]?.model ?? 'unknown'} (${cpus().length} logical CPUs visible) |`,
    `| OS | ${platform()} ${release()} ${arch()} |`,
    `| Runtime | ${process.versions.bun ? `Bun ${process.versions.bun}` : `Node ${process.version}`} |`,
    `| rustc available at measurement | ${command('rustc', ['--version'])} |`,
    `| wasm-pack available at measurement | ${command('wasm-pack', ['--version'])} |`,
    `| mathjs | ${require('mathjs/package.json').version} |`,
    `| WASM SHA-256 | ${createHash('sha256').update(bytes).digest('hex')} |`,
    `| WASM raw bytes | ${bytes.length} |`,
    `| WASM gzip bytes (level 9) | ${gzipSync(bytes, { level: 9 }).length} |`,
    '',
    '## Method',
    '',
    `Each case warms up with 1,000 evaluations per engine, then measures ${ITER.toLocaleString('en-US')} evaluations per run for ${RUNS} runs. The table reports median microseconds per operation.`,
    'Every iteration evaluates source text (parse + compile + execute) and produces a display string. Module loading, initialization and the application result cache are outside the timed loop. Engines run sequentially, math-box first. This is a warm throughput benchmark, not cold-start or UI latency.',
    '',
    'Unsupported mathjs syntax is marked n/a and has no speedup. The supported cases use the same expression text; this does not establish feature parity. Speedups use the unrounded medians, so ratios computed from displayed values may differ slightly.',
    '',
    '## Results',
    '',
    '| case | expression | math-box (µs/op) | mathjs (µs/op) | speedup |',
    '|---|---|---:|---:|---:|',
  ];

  for (const c of cases) {
    const mb = bench(`math-box::${c.name}`, () => mathBox.evaluate(c.expr));
    let mjLine = '— | —';
    try {
      // probe mathjs once before bench-loop; if it throws, mark as unsupported
      mjsEvaluate(c.expr);
      const mj = bench(`mathjs::${c.name}`, () => String(mjsEvaluate(c.expr)));
      const speedup = mj.us_per_op / mb.us_per_op;
      mjLine = `${mj.us_per_op.toFixed(2)} | ${speedup.toFixed(2)}×`;
    } catch {
      mjLine = `n/a | n/a`;
    }
    lines.push(
      `| ${c.name} | \`${c.expr}\` | ${mb.us_per_op.toFixed(2)} | ${mjLine} |`,
    );
  }
  lines.push(
    '',
    '## Reproduce',
    '',
    'Build the artifact from the checked-out source before benchmarking. The script loads `pkg/math_box.js` and `pkg/math_box_bg.wasm` directly, so an older installed file dependency cannot supply a stale binary. The hash and size above identify the actual artifact. Tool versions alone do not prove how an existing binary was built.',
    '',
    '```sh',
    'wasm-pack build --target web --release wasmModules/math-box',
    'bun install --frozen-lockfile',
    'node wasmModules/math-box/bench/compare.mjs --write',
    '```',
    '',
    'The default release build enables `std wasm bigint fraction unit complex`. `--write` replaces this report; without it, the report goes only to stdout. Keep the source revision and toolchain with any result you compare. This report replaces older phase tables whose commits and artifacts were not reproducibly identified.',
    '',
    'No native timing, feature-removal size delta, or mathjs bundle size is measured here. For the six native full-pipeline Criterion cases, run:',
    '',
    '```sh',
    'cd wasmModules/math-box',
    'cargo bench --no-default-features --features "std bigint fraction unit complex"',
    '```',
    '',
    'Disabling `unit` removes unit literals, `to`, unit values and the `unit`/`convert` functions. Unit syntax is already implemented. Bundle savings for a feature require separately built and measured artifacts.',
    '',
  );
  const report = lines.join('\n');
  if (process.argv.includes('--write'))
    await writeFile(new URL('../BENCHMARK.md', import.meta.url), report);
  console.log(report);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
