name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: deploy-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22
  PNPM_VERSION: 10
  GCP_PROJECT_ID: magic-box-b8bdc

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get git commit message
        if: github.event_name == 'pull_request'
        run: |
          git log --oneline origin/$GITHUB_BASE_REF..HEAD | tee commit-message

      - uses: codespell-project/codespell-problem-matcher@v1

      - name: Codespell
        uses: codespell-project/actions-codespell@master

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run ESLint
        run: pnpm lint

      # Upload built wasm modules
      - uses: actions/upload-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          name: wasm-modules
          path: wasmModules/*/pkg

  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs:
      - codespell
      - eslint
    steps:
      - uses: actions/checkout@v4

      # Download built wasm modules
      - uses: actions/download-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          name: wasm-modules
          path: wasmModules

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          buildWasm: false

      - name: Build
        run: pnpm build
        env:
          # NOTE: allow warnings
          # Treating warnings as errors because process.env.CI = true.
          CI: false

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAGIC_BOX_B8BDC }}'
          channelId: live
          projectId: ${{ env.GCP_PROJECT_ID }}
