name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 20

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run tests
        run: yarn test

  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          start: yarn start
          wait-on: http://localhost:3000

  rust-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        case:
          - wasmModules/base64-box
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        run: |
          cd ${{ matrix.case }}
          cargo test

