name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 20

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run tests
        run: yarn test

  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          start: yarn start
          wait-on: http://localhost:3000
