name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 22

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run tests
        run: pnpm test

  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Install Cypress
        run: pnpm exec cypress install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_DEBUG: 1
        with:
          component: true
          start: pnpm start
          wait-on: http://localhost:3000

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: warn
